#PACKAGE:star.tcsimulation
#STAR EXTERNAL STRINGS (US)
SimulationCreateActionExtension.field.CREATE_EXCEPT_MSG=Failed creating simulation from ${Branding.TEAMCENTER_APP_NAME}.
SimulationCreateActionExtension.field.DOWNLOAD_TEMPLATE_MSG=Failed downloading referenced template from ${Branding.TEAMCENTER_APP_NAME}.
