#PACKAGE:star.timefreqcoupling
#STAR EXTERNAL STRINGS (US)
FrequencyCouplingModel.bean.display=Time Frequency Coupling
FrequencyCouplingModel.bean.hint=Time-frequency coupling model
FrequencyCouplingSolver.bean.display=Time Frequency Coupling
FrequencyCouplingSolver.bean.hint=Time-frequency coupling solver
FrequencyPhysicsObjectManager.bean.display=Frequency Domain Continua
FrequencyPhysicsObjectManager.bean.hint=One or more continua, excluding continua with time models
ImmersedSource.ImmersedBoundariesInput.bean.property.display=Immersed Shell
ImmersedSource.ImmersedBoundariesInput.bean.property.hint=Immersed shell regions to transfer the time domain sources to the frequency domain
ImmersedSource.ImmersedBoundariesInput.bean.property.source_index=7.001
ImmersedSource.bean.display=Immersed Source
ImmersedSource.bean.hint=An acoustic immersed source
ImmersedSourceManager.bean.display=Immersed Sources
ImmersedSourceManager.bean.hint=Immersed sources
ImmersedSourcesModelFreq.bean.display=Immersed Sources
ImmersedSourcesModelFreq.bean.hint=Immersed discrete sources model
ImmersedSourcesModelTime.bean.display=Immersed Sources
ImmersedSourcesModelTime.bean.hint=Immersed discrete sources model
ImmersedSourcesSolver.Frozen.bean.property.display=Solver Frozen
ImmersedSourcesSolver.Frozen.bean.property.hint=This solver is frozen during iteration
ImmersedSourcesSolver.bean.display=Immersed Discrete Sources
ImmersedSourcesSolver.bean.hint=Immersed discrete sources solver
OverlapType$Type.field.FIFTY=50%
OverlapType$Type.field.SEVENTYFIVE=75%
OverlapType$Type.field.TWENTYFIVE=25%
OverlapType$Type.field.ZERO=0%
OverlapType.bean.display=Overlap
OverlapType.bean.hint=Overlap (%) for time segmentation
SignalProcessingFieldFunction.FrequencyIndexDefinition.bean.property.display=Frequency Index
SignalProcessingFieldFunction.FrequencyIndexDefinition.bean.property.hint=Frequency index
SignalProcessingFieldFunction.FrequencyIndexDefinition.bean.property.source_index=8.001
SignalProcessingFieldFunction.bean.display=Signal Processing Field Function
SignalProcessingFieldFunction.bean.hint=Signal Processing Field Function
TimeCouplingModel.bean.display=Time Frequency Coupling
TimeCouplingModel.bean.hint=Time-frequency coupling model
TimeCouplingSolver.bean.display=Time Frequency Coupling
TimeCouplingSolver.bean.hint=Time-frequency coupling solver
TimeFrequencyCouplingAutomationBlock.FrequencySimulationObjectsInput.bean.property.display=Frequency Simulation Objects
TimeFrequencyCouplingAutomationBlock.FrequencySimulationObjectsInput.bean.property.hint=One or more continua
TimeFrequencyCouplingAutomationBlock.FrequencySimulationObjectsInput.bean.property.source_index=6.002
TimeFrequencyCouplingAutomationBlock.TimeSimulationObjectsInput.bean.property.display=Time Simulation Objects
TimeFrequencyCouplingAutomationBlock.TimeSimulationObjectsInput.bean.property.hint=a) One or more continua, or b) One time scale
TimeFrequencyCouplingAutomationBlock.TimeSimulationObjectsInput.bean.property.source_index=6.001
TimeFrequencyCouplingAutomationBlock.bean.display=Solve Time-Frequency
TimeFrequencyCouplingAutomationBlock.bean.hint=Solve time-frequency coupling workflow
TimeFrequencyCouplingManager.bean.display=Time Frequency Coupling
TimeFrequencyCouplingManager.bean.hint=Time-Frequency Coupling Manager
TimeFrequencyCouplingMethod$Type.field.COMPUTE=Compute only
TimeFrequencyCouplingMethod$Type.field.READ=Read prerecorded data
TimeFrequencyCouplingMethod$Type.field.WRITE=Compute and write data
TimeFrequencyCouplingMethod$Type.field.WRITE_READ=Compute, write and read data
TimeFrequencyCouplingMethod.bean.display=Method
TimeFrequencyCouplingMethod.bean.hint=Select method for retrieving for time-frequency source data
TimeFrequencyCouplingModel.bean.display=Time Frequency Coupling
TimeFrequencyCouplingModel.bean.hint=Time-frequency coupling model
TimeFrequencyCouplingObject.CoordinateSystem.bean.property.display=Coordinate System
TimeFrequencyCouplingObject.CoordinateSystem.bean.property.hint=Coordinate system in which the track file positions are defined
TimeFrequencyCouplingObject.CoordinateSystem.bean.property.source_index=6.002
TimeFrequencyCouplingObject.MethodInput.bean.property.display=Method
TimeFrequencyCouplingObject.MethodInput.bean.property.hint=Method for handling immersed source data
TimeFrequencyCouplingObject.MethodInput.bean.property.source_index=6.001
TimeFrequencyCouplingObject.bean.display=Time Frequency Coupling Object
TimeFrequencyCouplingObject.bean.hint=A representation of the spatial time-frequency coupling
TimeFrequencyCouplingObjectManager.bean.display=Time Frequency Coupling Objects
TimeFrequencyCouplingObjectManager.bean.hint=Time Frequency Coupling objects
TimeFrequencyCouplingSolver.BlockLengthInput.bean.property.display=Block Duration
TimeFrequencyCouplingSolver.BlockLengthInput.bean.property.hint=Duration of each spectrum block
TimeFrequencyCouplingSolver.BlockLengthInput.bean.property.source_index=5.004
TimeFrequencyCouplingSolver.CurrentBlock.bean.property.display=Current Block
TimeFrequencyCouplingSolver.CurrentBlock.bean.property.hint=Current spectrum block
TimeFrequencyCouplingSolver.CurrentBlock.bean.property.source_index=5.002
TimeFrequencyCouplingSolver.EndTimeInput.bean.property.display=End Time
TimeFrequencyCouplingSolver.EndTimeInput.bean.property.hint=End time
TimeFrequencyCouplingSolver.EndTimeInput.bean.property.source_index=5.007
TimeFrequencyCouplingSolver.FrequencyStepInput.bean.property.display=Frequency Step
TimeFrequencyCouplingSolver.FrequencyStepInput.bean.property.hint=Frequency step impacting time segmentation
TimeFrequencyCouplingSolver.FrequencyStepInput.bean.property.source_index=5.008
TimeFrequencyCouplingSolver.Frozen.bean.property.display=Solver Frozen
TimeFrequencyCouplingSolver.Frozen.bean.property.hint=This solver is frozen during iteration
TimeFrequencyCouplingSolver.MaxFrequencyInput.bean.property.display=Maximum Frequency
TimeFrequencyCouplingSolver.MaxFrequencyInput.bean.property.hint=Maximum frequency
TimeFrequencyCouplingSolver.MaxFrequencyInput.bean.property.source_index=5.009
TimeFrequencyCouplingSolver.NumberOfBlocks.bean.property.display=Number of Blocks
TimeFrequencyCouplingSolver.NumberOfBlocks.bean.property.hint=Number of spectrum blocks
TimeFrequencyCouplingSolver.NumberOfBlocks.bean.property.source_index=5.003
TimeFrequencyCouplingSolver.OverlapTypeInput.bean.property.display=Overlap
TimeFrequencyCouplingSolver.OverlapTypeInput.bean.property.hint=Overlap (%) for time segmentation
TimeFrequencyCouplingSolver.OverlapTypeInput.bean.property.source_index=5.010
TimeFrequencyCouplingSolver.StartTimeInput.bean.property.display=Start Time
TimeFrequencyCouplingSolver.StartTimeInput.bean.property.hint=Start time
TimeFrequencyCouplingSolver.StartTimeInput.bean.property.source_index=5.006
TimeFrequencyCouplingSolver.Verbosity.bean.property.display=Verbosity
TimeFrequencyCouplingSolver.Verbosity.bean.property.hint=Verbosity Level
TimeFrequencyCouplingSolver.Verbosity.bean.property.source_index=5.005
TimeFrequencyCouplingSolver.WindowTypeInput.bean.property.display=Window Function
TimeFrequencyCouplingSolver.WindowTypeInput.bean.property.hint=Window function applied during time to frequency transform
TimeFrequencyCouplingSolver.WindowTypeInput.bean.property.source_index=5.011
TimeFrequencyCouplingSolver.WorkflowOptionInput.bean.property.display=Workflow Option
TimeFrequencyCouplingSolver.WorkflowOptionInput.bean.property.hint=Choose how to run the time frequency workflow (in-memory, file-based). The available options depend on the active continuum or time scale containing the Time Frequency Coupling Model.
TimeFrequencyCouplingSolver.WorkflowOptionInput.bean.property.source_index=5.012
TimeFrequencyCouplingSolver.bean.display=Time Frequency Coupling
TimeFrequencyCouplingSolver.bean.hint=Time-frequency coupling solver
TimeFrequencyWorkflowOption$Type.field.IN_CORE_MEM=In-memory
TimeFrequencyWorkflowOption$Type.field.OUT_OF_CORE_FREQ_READ=File-based
TimeFrequencyWorkflowOption$Type.field.OUT_OF_CORE_FREQ_READ_WRITE=File-based
TimeFrequencyWorkflowOption$Type.field.OUT_OF_CORE_FREQ_WRITE=File-based
TimeFrequencyWorkflowOption.bean.display=Workflow
TimeFrequencyWorkflowOption.bean.hint=Select workflow (in-memory, file-based) for time-frequency coupling solver
TimePhysicsObjectManager.bean.display=Time Domain Continua or Time Scale
TimePhysicsObjectManager.bean.hint=One or more continua, or, one time scale, excluding continua with frequency models
TrackFileCoupling.bean.display=Track File
TrackFileCoupling.bean.hint=Track file for time-frequency coupling
TrackFileHandler.BaseName.bean.property.display=Base Filename
TrackFileHandler.BaseName.bean.property.hint=Base filename for out-of-core run
TrackFileHandler.BaseName.bean.property.source_index=4.003
TrackFileHandler.ExportDirectory.bean.property.display=Export Directory
TrackFileHandler.ExportDirectory.bean.property.hint=Directory to export track files (. sim file directory)
TrackFileHandler.ExportDirectory.bean.property.source_index=4.002
TrackFileHandler.ReadBase.bean.property.display=Base Filename
TrackFileHandler.ReadBase.bean.property.hint=Base filename of a .trk file for out-of-core run
TrackFileHandler.ReadBase.bean.property.source_index=4.001
TrackFileHandler.UseReadBaseName.bean.property.display=Use Read Base Name
TrackFileHandler.UseReadBaseName.bean.property.hint=Use the read base name for out-of-core run
TrackFileHandler.bean.display=Track file (file-based)
TrackFileHandler.bean.hint=Track file properties for file-based time-frequency coupling
TrackFileHandler.field.TRACK_FILES=Track files (*.trk)
TrackPointGenerator.bean.display=PointSet from Track File
TrackPointGenerator.bean.hint=Automatic point set generation from track file
TrackPointSet.bean.display=Track Point Set
TrackPointSet.bean.hint=A set of points from track file
WindowType$Type.field.BLACKMAN=Blackman
WindowType$Type.field.HAMMING=Hamming
WindowType$Type.field.HANNING=Hann
WindowType$Type.field.RECTANGULAR=None
WindowType.bean.display=Window Type
WindowType.bean.hint=Window type for Fourier transform
