#PACKAGE:star.tcmdx
#STAR EXTERNAL STRINGS (US)
MdxCreateActionExtension.field.DOWNLOAD_ERROR_MSG=Failed to download JSON for PLMXML
MdxCreateActionExtension.field.IMPORT_ERROR_MSG=Failed importing JSON
MdxPublishActionExtension.field.MDX_PUBLISH_EXCEPT_MSG=Failed publishing MDX object.
MdxRepublishActionExtension.field.MDX_REPUBLISH_EXCEPT_MSG=Failed publishing MDX object.
