#PACKAGE:star.automation
#STAR EXTERNAL STRINGS (US)
MeshAutomationBlock.ExecuteAllMeshOperations.bean.property.display=Execute All Mesh Operations
MeshAutomationBlock.ExecuteAllMeshOperations.bean.property.hint=Execute all mesh operations or only the selected ones
MeshAutomationBlock.ExecuteAllMeshOperations.bean.property.source_index=6.001
MeshAutomationBlock.MeshOperationsInput.bean.property.display=Mesh Operations
MeshAutomationBlock.MeshOperationsInput.bean.property.hint=The mesh operations to execute
MeshAutomationBlock.MeshOperationsInput.bean.property.source_index=6.002
MeshAutomationBlock.bean.display=Mesh
MeshAutomationBlock.bean.hint=Meshing for Simulation Operations
