#PACKAGE:star.parameterization.actions
#STAR EXTERNAL STRINGS (US)
HighlightMaxParameterPartsInCurrentSceneAction.action.name=Highlight Max
HighlightMeridionalInterfaceParameterPartsInCurrentSceneAction.action.name=Highlight Interfaces
HighlightMinParameterPartsInCurrentSceneAction.action.name=Highlight Min
HighlightProfileInCurrentSceneAction.action.name=Highlight Profile
HighlightSpanwiseProfileInCurrentSceneAction.action.name=Highlight Profiles
