#PACKAGE:star.virtualbody.ui
#STAR EXTERNAL STRINGS (US)
AssignPartsToVirtualBodyBoundaryDialog.dialog.title=Create Virtual Body Boundaries and Assign Parts
AssignPartsToVirtualBodyBoundaryDialog.field.CREATE_ONE_LABEL=Create One Virtual Body Boundary for All Part Surfaces
AssignPartsToVirtualBodyBoundaryDialog.field.DEFAULT_BOUNDARY_NAME=Virtual Body Boundary
AssignPartsToVirtualBodyBoundaryDialog.field.PER_PARTSURFACE_LABEL=Create a Virtual Body Boundary for Each Part Surface
AssignPartsToVirtualBodyBoundaryDialog.field.PER_PART_LABEL=Create a Virtual Body Boundary for Each Part
AssignPartsToVirtualBodyBoundaryDialog.field.USE_EXISTING_LABEL=Assign All Part Surfaces to an Existing Virtual Body Boundary
