#PACKAGE:star.teamcenter.actions
#STAR EXTERNAL STRINGS (US)
CreateAction.action.name=Create
CreateAction.field.CREATE_EXCEPT_MSG=Failed creating object from ${Branding.TEAMCENTER_APP_NAME}.
CreateAction.field.DOWNLOAD_TEMPLATE_MSG=Failed downloading referenced template from ${Branding.TEAMCENTER_APP_NAME}.
CreateAction.field.DO_ACTION_MSG=Completed downloading ${Branding.TEAMCENTER_APP_NAME} '%s'; proceed to create?
CreateAction.field.DO_ACTION_TITLE=${Branding.STAR_CCM_APP_NAME} download complete.
CreateAction.field.TEAMCENTER_EXCEPT_MSG=Failed getting contents from ${Branding.TEAMCENTER_APP_NAME}.
CreateAction.field.TITLE=Create a File
ImportGeometryAction.action.name=Import Geometry
ImportGeometryAction.field.DO_ACTION_MSG=Completed downloading ${Branding.TEAMCENTER_APP_NAME} '%s'; proceed to import geometry?
ImportGeometryAction.field.DO_ACTION_TITLE=${Branding.STAR_CCM_APP_NAME} download complete.
ImportGeometryAction.field.IMPORT_EXCEPT_MSG=Failed downloading geometry from ${Branding.TEAMCENTER_APP_NAME}.
ImportGeometryAction.field.LINK_FAIL_MSG=Failed linking geometry to simulation in ${Branding.TEAMCENTER_APP_NAME}.
ImportSimulationAction.action.name=Import Simulation
ImportSimulationAction.field.LINK_FAIL=Failed linking geometry to simulation in ${Branding.TEAMCENTER_APP_NAME}.
OpenAction.action.name=Open
OpenAction.field.OPEN_FAILED_MSG=Open action failed
OpenActiveWorkspaceAction.action.name=Open Active Workspace
OpenActiveWorkspaceAction.field.CANCEL=Cancel
OpenActiveWorkspaceAction.field.LOGIN=Login
OpenActiveWorkspaceAction.field.TITLE=Enter ${Branding.TEAMCENTER_APP_NAME} Credentials
PublishAction.action.name=Publish
PublishAction.field.PUBLISH_EXCEPT_MSG=Failed publishing to ${Branding.TEAMCENTER_APP_NAME}.
PublishAction.field.SAVE_CHANGES=Simulation must be saved before publishing.  Save Changes?
PublishAction.field.SAVE_CHANGES_TITLE=Save Changes
PublishAction.field.SAVE_STAGING=Simulation must be saved to ${Branding.TEAMCENTER_APP_NAME} staging directory before publishing.  Save Changes?
PublishAction.field.SAVE_STAGING_TITLE=Save To ${Branding.TEAMCENTER_APP_NAME} staging
PublishTemplateAction.action.name=Publish As Template
PublishTemplateAction.field.PUBLISH_EXCEPT_MSG=Failed publishing  simulation template to ${Branding.TEAMCENTER_APP_NAME}.
PublishTemplateAction.field.SAVE_FAIL_MSG=Failed saving as template to ${Branding.TEAMCENTER_APP_NAME} staging
PublishTemplateAction.field.SAVE_STAGING=Simulation template must be saved to ${Branding.TEAMCENTER_APP_NAME} staging directory before publishing. Save Changes?
PublishTemplateAction.field.SAVE_STAGING_TITLE=Save To ${Branding.TEAMCENTER_APP_NAME} staging
RepublishAction.action.name=Republish
RepublishAction.field.NO_APPTYPE_MSG=Could not get application type
RepublishAction.field.REPUBLISH_EXCEPT_MSG=Failed republishing simulation to ${Branding.TEAMCENTER_APP_NAME}.
RepublishAction.field.SAVE_CHANGES=Changes to simulation must be saved before publishing.  Save Changes?
RepublishAction.field.SAVE_CHANGES_TITLE=Save Changes
TeamcenterMenuAction.field.FAILED_APP_TYPE_MSG=Failed to get Application Type
TeamcenterMenuActionHelper.field.CONFIRM_TITLE=Confirm
TeamcenterMenuActionHelper.field.DEFAULT_ACTION_NAME=perform action
TeamcenterMenuActionHelper.field.ERROR_TEMPLATE=Failed to %s from ${Branding.TEAMCENTER_APP_NAME}.
TeamcenterMenuActionHelper.field.PROMPT_TEMPLATE=Completed downloading ${Branding.TEAMCENTER_APP_NAME} '%1$s'; proceed to %2$s?
TeamcenterMenuActionHelper.field.WARNING_MSG=Could not get filtered contents
