#PACKAGE:star.tcs
#STAR EXTERNAL STRINGS (US)
TcsDownload.field.DOWNLOADING=Downloading...
TcsDownload.field.FAILED=Failed
TcsDownloadCellRendererPanel.field.CANCEL_BUTTON=Cancel
TcsDownloadCellRendererPanel.field.COPY_PATH_BUTTON=Copy Path
TcsDownloadCellRendererPanel.field.OPEN_SIM_BUTTON=Open Simulation
TcsDownloadCellRendererPanel.field.PAUSE_BUTTON=Pause
TcsDownloadCellRendererPanel.field.RESUME_BUTTON=Resume
TcsDownloadJxBrowser.field.DOWNLOAD_CANCELLED=Download cancelled
TcsDownloadJxBrowser.field.DOWNLOAD_COMPLETED=Download completed
TcsDownloadJxBrowser.field.DOWNLOAD_INTERRUPTED=Download interruped
TcsDownloadJxBrowser.field.DOWNLOAD_PAUSED=Download paused
TcsDownloadJxBrowser.field.EXTRACTING_ZIP=Download completed, Extracting zip file...
TcsDownloadTopComponent.field.ACTION_COLUMN=Action
TcsDownloadTopComponent.field.FILE_COLUMN=File
TcsDownloadTopComponent.field.STATUS_COLUMN=Status
TcsDownloadTopComponent.field.TCS_DOWNLOADS_TAB_NAME=${Branding.TEAMCENTER_SHARE_APP_NAME} Downloads
TeamcenterShareTopComponent.field.FILE_EXISTS=The file with given name already exists.\nPlease select another name.
TeamcenterShareTopComponent.field.INFOBOX_TITLE=No URL found
TeamcenterShareTopComponent.field.NO_URL_FOUND=The ${Branding.TEAMCENTER_SHARE_APP_NAME} URL is not configured properly.
